export { default as schemeCategory10 } from './categorical/category10.ts'
export { default as schemeAccent } from './categorical/Accent.ts'
export { default as schemeDark2 } from './categorical/Dark2.ts'
export { default as schemeObservable10 } from './categorical/observable10.ts'
export { default as schemePaired } from './categorical/Paired.ts'
export { default as schemePastel1 } from './categorical/Pastel1.ts'
export { default as schemePastel2 } from './categorical/Pastel2.ts'
export { default as schemeSet1 } from './categorical/Set1.ts'
export { default as schemeSet2 } from './categorical/Set2.ts'
export { default as schemeSet3 } from './categorical/Set3.ts'
export { default as schemeTableau10 } from './categorical/Tableau10.ts'
export { default as interpolateBrBG, scheme as schemeBrBG } from './diverging/BrBG.ts'
export { default as interpolatePRGn, scheme as schemePRGn } from './diverging/PRGn.ts'
export { default as interpolatePiYG, scheme as schemePiYG } from './diverging/PiYG.ts'
export { default as interpolatePuOr, scheme as schemePuOr } from './diverging/PuOr.ts'
export { default as interpolateRdBu, scheme as schemeRdBu } from './diverging/RdBu.ts'
export { default as interpolateRdGy, scheme as schemeRdGy } from './diverging/RdGy.ts'
export { default as interpolateRdYlBu, scheme as schemeRdYlBu } from './diverging/RdYlBu.ts'
export { default as interpolateRdYlGn, scheme as schemeRdYlGn } from './diverging/RdYlGn.ts'
export { default as interpolateSpectral, scheme as schemeSpectral } from './diverging/Spectral.ts'
export { default as interpolateBuGn, scheme as schemeBuGn } from './sequential-multi/BuGn.ts'
export { default as interpolateBuPu, scheme as schemeBuPu } from './sequential-multi/BuPu.ts'
export { default as interpolateGnBu, scheme as schemeGnBu } from './sequential-multi/GnBu.ts'
export { default as interpolateOrRd, scheme as schemeOrRd } from './sequential-multi/OrRd.ts'
export { default as interpolatePuBuGn, scheme as schemePuBuGn } from './sequential-multi/PuBuGn.ts'
export { default as interpolatePuBu, scheme as schemePuBu } from './sequential-multi/PuBu.ts'
export { default as interpolatePuRd, scheme as schemePuRd } from './sequential-multi/PuRd.ts'
export { default as interpolateRdPu, scheme as schemeRdPu } from './sequential-multi/RdPu.ts'
export { default as interpolateYlGnBu, scheme as schemeYlGnBu } from './sequential-multi/YlGnBu.ts'
export { default as interpolateYlGn, scheme as schemeYlGn } from './sequential-multi/YlGn.ts'
export { default as interpolateYlOrBr, scheme as schemeYlOrBr } from './sequential-multi/YlOrBr.ts'
export { default as interpolateYlOrRd, scheme as schemeYlOrRd } from './sequential-multi/YlOrRd.ts'
export { default as interpolateBlues, scheme as schemeBlues } from './sequential-single/Blues.ts'
export { default as interpolateGreens, scheme as schemeGreens } from './sequential-single/Greens.ts'
export { default as interpolateGreys, scheme as schemeGreys } from './sequential-single/Greys.ts'
export { default as interpolatePurples, scheme as schemePurples } from './sequential-single/Purples.ts'
export { default as interpolateReds, scheme as schemeReds } from './sequential-single/Reds.ts'
export { default as interpolateOranges, scheme as schemeOranges } from './sequential-single/Oranges.ts'
export { default as interpolateCividis } from './sequential-multi/cividis.ts'
export { default as interpolateCubehelixDefault } from './sequential-multi/cubehelix.ts'
export { default as interpolateRainbow, warm as interpolateWarm, cool as interpolateCool } from './sequential-multi/rainbow.ts'
export { default as interpolateSinebow } from './sequential-multi/sinebow.ts'
export { default as interpolateTurbo } from './sequential-multi/turbo.ts'
export { default as interpolateViridis, magma as interpolateMagma, inferno as interpolateInferno, plasma as interpolatePlasma } from './sequential-multi/viridis.ts'
